# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0104c6f113f02bc01095c7436a101e60405b17681226105e4ce786851a4f73595c8b6f5f9910c38b6dac77e46ce14d1a82e5506a4ceddb20cd820f0cb9aa0ac9

test:
  secret_key_base: be37c1b5761fad69810dd4218a68ceef26cc9bda664f5d4f670aab932e88e3e740fc2eb79fbacced3c4ed210707bc5dc812b8e63cb5e20f1fad49b8987594060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
